controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

client_prenom:
  path: /client/prenom/{prenom}
  controller: App\Controller\ClientController::info
  requirements:
        prenom: '^[a-zA-Z]+(-[a-zA-Z]+)*$'


route_image:
  path: /stockage
  controller: App\Controller\StockageController::home

route_home:
  path: /
  controller: App\Controller\DefaultController::redirectToStockage


